### ISSUE TITLE
Click Events In Tasks

### ISSUE THREAD

**Issue by mariohmol** [mariohmol/jsgantt-improved#1]
## click event specific cell

This feature allows you to independently capture events in cells, for that use the setEventsClickCell(events). Where events is a object with the attrs: (task, resource, duration, complete, startdate, enddate). All should be functions.

## click event row

This feature allow you capture events in a row and get the data of task

## double click event row

This feature is equals to click event row but is handler in a dblclick event

# Tips

In case it is not possible to get data from my fork. Here's the tutorial on how I did it:

Basically, we'll make changes to two functions. These functions are GanttChart and Draw.

GanttChart()
In this method we will create a variable of type object like this:

var vEvents = {
		task: null,
		resource: null,
		duration: null,
		complete: null,
		startdate: null,
		enddate: null
	};
Still in this method, add the following code:

this.setEventsClickCell=function(pEvents){vEvents=pEvents;}
This code will allow a method to be attached to the chart object, and passing an object with the functions can access the functions it will execute.

Draw()
Changes made in the GanttChart() method are for preparation only and for saving the data. It is in the Draw() method that the action will actually occur.

First of all, in the vTaskList loop you need to add a dataset in the cells. This dataset will allow information to be retrieved when the event is executed. See:

vTmpCell.dataset.id = vID;
vTmpCell.dataset.name = vName;
vTmpCell.dataset.group = vGroup;
vTmpCell.dataset.level = vLevel;
After that we will use the JSGantt.addListener() to add a click event. See:

JSGantt.addListener('click', function(){
    if(typeof vEvents.task === "function"){
        vEvents.task(this.dataset, this);
    }
}, vTmpCell);
This method receives three parameters. The first is the event type, the second is the function that will be executed and the third is the element that will be receive the event.

Note that no code snippet above is adding a click event to the vTmpCell HTML element (which will be a table cell). In the execution function we make a check if a function for that event has been defined.
If there is a function, we execute it by passing the dataset and the HTML element as callback.

Here's another code snippet:

if(vShowRes==1){
    vTmpCell=this.newNode(vTmpRow, 'td', null, 'gresource');
    vTmpDiv=this.newNode(vTmpCell, 'div', null, null, vTaskList[i].getResource());
   
    // start edition
    vTmpCell.dataset.res = vRes;
    JSGantt.addListener('click', function(){
        if(typeof vEvents.resource === "function"){
            vEvents.resource(this.dataset.res, this);
        }
     }, vTmpCell);
    // end edition
}
In the above code snippet we have a check. if (vShowRes == 1). This check sets whether to display a particular cell.

The default block has only the first two lines. More to add the events you need to change it and add the content that I marked by the comments start edition and end edition.

See also that we added the dataset. We need to do this for each cell, because the value of the vTmpCell variable will be different for each cell. Therefore, these checks are required for each cell.

This is why the vEvents object has one attribute for each column.

Conclusion
These are the modifications needed to add click event to the cell. On my fork there is also implementation to click on the line.

I hope this explanation can help. You can download the file from my fork (see https://github.com/geeksilva97/jsgantt-improved/).
The only changed file is jsgantt.js and the way to use it is in the test folder.

**Comment by geeksilva97** [comment]
Ok, I go.

**Comment by mariohmol** [comment]
Going to main repo
